name: CI

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
      JWT_SECRET_KEY: 73bc12b7555ceeba4e41d7717906ca8b5ed540b190310db8f23d450a596440a79d90179cd9b584e213d42cdd2434dd97003f45fd255aa7c84f85a012f060adf0
    runs-on: ubuntu-latest # runner
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository # copies repo in runner
        uses: actions/checkout@v2 # short for https://github.com/actions/checkout
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Get Yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prepare DB
        run: |
          cp config/database.github.yml config/database.yml
          bundle exec rails db:create db:migrate
      - name: Run RSpec tests
        run: bundle exec rspec -f d --tag ~js --tag ~flaky --tag ~quarantine
      - name: Run RSpec JS tests
        run: bundle exec rspec -f d --tag js --tag ~flaky --tag ~quarantine
      - name: Run RSpec flaky tests
        run: bundle exec rspec -f d --tag flaky
        continue-on-error: true
      - name: Run RSpec quarantine tests
        run: bundle exec rspec -f d --tag quarantine
        continue-on-error: true
      - name: Run Vitest tests
        run: yarn test